#!/usr/bin/env bash
# This script prints 10 iterations
# 4th iteration --> "bad_luck"
# 8th iteration --> "good_luck"
# Other iterations --> "Best School"

i=1
while [ $i -le 10 ]
do
  
  if [[ "$i" == "4" ]]
  then
    echo "bad luck"
  else
    echo "Best School"
  fi
  ((i++))
done
