#!/usr/bin/env bash
# This script prints 10 iterations
# After the 4th iteration --> "bad luck from China"
# After the 9th iteration --> "bad luck from Japan"
# Other iterations --> "Best School"

i=1
while [ $i -le 20 ]
do
  echo "$i"

  case $i in
  4)
    echo "bad luck from China"
  ;;
  9)
    echo "bad luck from Japan"
  ;;
  17)
    echo "bad luck from Italy"
  esac
  ((i++))
done
