#!/usr/bin/env bash
# This script prints 10 iterations
# After the 4th iteration --> "bad luck from China"
# After the 9th iteration --> "bad luck from Japan"
# Other iterations --> "Best School"

i=1
while [ $i -le 20 ]
do
  echo "$i"
  if [[ "$i" == "4" ]]
  then
    echo "bad luck from China"
  elif [[ "$i" == 9 ]]
  then
    echo "bad luck from Japan"
  elif [[ "$i" == 17 ]]
  then
    echo "bad luck form Italy"
  fi
  ((i++))
done
